src/Todo/ViewComponents/TodoItemAddViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Threading.Tasks;
using Todo.Interfaces;
using Todo.Models.TodoViewModels;

namespace Todo.ViewComponents
{
    public class TodoItemAddViewComponent : ViewComponent
    {
        private readonly ITodoRepository _todoRepository;

        public TodoItemAddViewComponent(ITodoRepository todoRepository)
        {
            _todoRepository = todoRepository;
        }

        public async Task<IViewComponentResult> InvokeAsync(int? id = null)
        {
            var todoItemVM = new TodoItemViewModel();
            if(id != null)
            {
                var todoItem = await _todoRepository.Find((int)id);

                todoItemVM.TodoItemID = todoItem.TodoItemID;
                todoItemVM.Name = todoItem.Name;
                todoItemVM.Description = todoItem.Description;
                todoItemVM.Status = todoItem.Status;
                todoItemVM.DateStart = todoItem.DateStart;
                todoItemVM.DateEnd = todoItem.DateEnd;
            }

            return View(todoItemVM);
        }
    }
}

src/Todo/ViewComponents/TodoItemListViewComponent.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Todo.Interfaces;
using Todo.Models;
using Todo.Models.TodoViewModels;

namespace Todo.ViewComponents
{
    public class TodoItemListViewComponent : ViewComponent
    {
        private readonly ITodoRepository _todoRepository;
        private readonly UserManager<ApplicationUser> _userManager;

        public TodoItemListViewComponent(ITodoRepository todoRepository, UserManager<ApplicationUser> userManager)
        {
            _todoRepository = todoRepository;
            _userManager = userManager;
        }

        public async Task<IViewComponentResult> InvokeAsync(bool showAllItems, bool delete, bool update)
        {
            var user = await _userManager.GetUserAsync(HttpContext.User);

            var todoItems = showAllItems ?
                _todoRepository.FindByUser(user) 
              : _todoRepository.FindByUserUnfinished(user);

            var todoItemsVM = from item in todoItems
                            select new TodoItemViewModel()
                            {
                                TodoItemID = item.TodoItemID,
                                Name = item.Name,
                                Status = item.Status,
                                Description = item.Description,
                                DateStart = item.DateStart,
                                DateEnd = item.DateEnd
                            };

            ViewBag.Delete = delete;
            ViewBag.Update = update;

            return View(todoItemsVM);
        }
    }
}

src/Todo/Views/Shared/Components/TodoItemListAdd/Default.cshtml
@model IEnumerable<TodoItemViewModel>
@inject SignInManager<ApplicationUser> SignInManager
@inject UserManager<ApplicationUser> UserManager

@{
    ViewData["Title"] = "Home Page";
}

<div class="row">
    <div class="container">
        
                    <h1>Todos</h1>
                    @if (SignInManager.IsSignedIn(User))
                    {
                        <div>
                            @await Component.InvokeAsync("TodoItemAdd")
                        </div>
                        <br />
                        @await Component.InvokeAsync("TodoItemList", new { showAllItems = false, delete = false, update = false })
                    }
                    else
                    {
                        <h3>Please sign in to see yours todo list.</h3>
                    }
                </div>
            </div>
@section Scripts {
    @{ await Html.RenderPartialAsync("_ValidationScriptsPartial"); }
}